apiVersion: apps/v1
kind: Deployment
metadata:
  name: college-search
  labels:
    app: college-search
spec:
  replicas: 2
  template:
    metadata:
      name: college-search
      labels:
        app: college-search
    spec:
      containers:
        - name: college-search
          image: life14ok/college-search
          ports:
            - containerPort: 10003
          env:
            - name: "PORT"
              value: "10003"
  selector:
    matchLabels:
      app: college-search
---
apiVersion: v1
kind: Service
metadata:
  name: college-search-service
spec:
  selector:
    app: college-search
  ports:
    - port: 10003
      targetPort: 10003
  type: LoadBalancer
