server:
  port: 10003
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

api-key: Z2wg5SZt8nPIC4JDHVzonL8ltMGYPc9IxhQMkrhL
api-url: https://api.data.gov/ed/collegescorecard/v1/schools.json?
